### ISSUE TITLE
Design Changes

### ISSUE THREAD

**Issue by RobLoach** [zetsingithub/node-sdl2#1]
What are your thoughts on...
- [x] Make each module module export `libraries` and `properties`, which are aggregated all together in `index.js`. The result would move all modules to the root so that referencing them would be easy:
  
  ``` javascript
  var sdl = require('node-sdl2');
  if (sdl.SDL_Init(sdl.SDL_INIT_VIDEO) != 0) {
    console.log('SDL_Init Error: ' + sdl.SDL_GetError());
    process.exit(1);
  }
  ```
  - `libraries` would be an associative array of the path of the library to load, along with all of the function definitions
  - `properties` would be an associative array that's merged in after libraries have been loaded
  
  This would make it really easy to port existing C code over to JavaScript.
- [x] Refactor the library loading to discover the library path (it's just `"libSDL2"` on Linux)
- [x] Remove the binaries from this package
- [ ] Move to some of ES2015?
- [x] Move SDL_Image to its own package: https://github.com/robloach/node-sdl2-image
- [x] Implement additional packages:
  - [x] [node-sdl2-mixer](https://github.com/RobLoach/node-sdl2-mixer)
  - [x] [node-sdl2-image](https://github.com/RobLoach/node-sdl2-image)
  - [x] [node-sdl2-gfx](https://github.com/robloach/node-sdl2-gfx)
  - [x] [node-sdl-ttf](https://github.com/robloach/node-sdl-ttf)

Took this on in https://github.com/zetsingithub/node-sdl2/pull/2

**Comment by zetsin** [comment]
I have re-generated all SDL2-FFI by [libclang](http://clang.llvm.org/get_started.html), however, #define macro are missing. See my new repository [node-ffi-gen](https://github.com/zetsingithub/node-ffi-gen).

**Comment by happilymarrieddad** [comment]
Hey guys, I'm getting this error on Linux Mint 18 (Ubuntu 16.04)

 return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'libSDL2.so'
    at Object.fs.openSync (fs.js:652:18)
    at fs.readFileSync (fs.js:553:33)
    at new DynamicLibrary (/home/nick/Projects/Nodejs/sdl/test/node_modules/ffi/lib/dynamic_library.js:67:21)
    at Object.Library (/home/nick/Projects/Nodejs/sdl/test/node_modules/ffi/lib/library.js:45:12)
    at Object.<anonymous> (/home/nick/Projects/Nodejs/sdl/test/node_modules/node-sdl2/dep/SDL_stdinc.js:74:5)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

This is what I ran
sudo apt-get install build-essential xorg-dev libudev-dev libts-dev libgl1-mesa-dev libglu1-mesa-dev libasound2-dev libpulse-dev libopenal-dev libogg-dev libvorbis-dev libaudiofile-dev libpng12-dev libfreetype6-dev libusb-dev libdbus-1-dev zlib1g-dev libdirectfb-dev

☁  test  sudo ln -s /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0 /usr/lib/libSDL2.so
[sudo] password for nick: 
☁  test  sudo ln -s /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0 /usr/local/lib/libSDL2.so

Thanks!

**Comment by happilymarrieddad** [comment]
sudo apt-get install libsdl2-dev

That fixed it
